use std::collections::HashMap;

use orbitdock_protocol::{
  ApprovalType, ClaudeModelOption, McpAuthStatus, McpResource, McpResourceTemplate,
  McpStartupFailure, McpStartupStatus, McpTool, SkillErrorInfo, SkillsListEntry, SubagentInfo,
  TokenUsage, TokenUsageSnapshotKind,
};

/// Connector events that are safe to feed into the reducer.
#[derive(Debug, Clone)]
pub enum ConnectorStateEvent {
  /// Turn started
  TurnStarted,

  /// Turn completed
  TurnCompleted,

  /// Turn aborted
  TurnAborted { reason: String },

  /// New conversation row created
  ConversationRowCreated(orbitdock_protocol::conversation_contracts::ConversationRowEntry),

  /// Conversation row updated
  ConversationRowUpdated {
    row_id: String,
    entry: orbitdock_protocol::conversation_contracts::ConversationRowEntry,
  },

  /// Approval requested
  ApprovalRequested {
    request_id: String,
    approval_type: ApprovalType,
    tool_name: Option<String>,
    tool_input: Option<String>,
    command: Option<String>,
    file_path: Option<String>,
    diff: Option<String>,
    question: Option<String>,
    permission_reason: Option<String>,
    requested_permissions: Option<serde_json::Value>,
    proposed_amendment: Option<Vec<String>>,
    /// Raw permission suggestions from Claude SDK (PermissionUpdate[])
    permission_suggestions: Option<serde_json::Value>,
    /// MCP elicitation mode: "form" or "url"
    elicitation_mode: Option<String>,
    /// JSON Schema for form-mode elicitation
    elicitation_schema: Option<serde_json::Value>,
    /// URL for browser-auth-mode elicitation
    elicitation_url: Option<String>,
    /// Human-readable message from the MCP server
    elicitation_message: Option<String>,
    /// Which MCP server initiated the elicitation
    mcp_server_name: Option<String>,
    /// Network approval context: target host
    network_host: Option<String>,
    /// Network approval context: protocol (e.g. "https")
    network_protocol: Option<String>,
  },

  /// Approval cancelled by the CLI (e.g. user interrupted, agent moved on)
  ApprovalCancelled { request_id: String },

  /// Permission mode changed (e.g. plan mode entered/exited)
  PermissionModeChanged { mode: String },

  /// Token usage updated
  TokensUpdated {
    usage: TokenUsage,
    snapshot_kind: TokenUsageSnapshotKind,
  },

  /// Aggregated diff updated
  DiffUpdated(String),

  /// Plan updated
  PlanUpdated(String),

  /// Thread name updated (auto-generated by codex-core or manually set)
  ThreadNameUpdated(String),

  /// Session ended
  SessionEnded { reason: String },

  /// Skills list response
  SkillsList {
    skills: Vec<SkillsListEntry>,
    errors: Vec<SkillErrorInfo>,
  },

  /// Skills update available notification
  SkillsUpdateAvailable,

  /// MCP tools list response
  McpToolsList {
    tools: HashMap<String, McpTool>,
    resources: HashMap<String, Vec<McpResource>>,
    resource_templates: HashMap<String, Vec<McpResourceTemplate>>,
    auth_statuses: HashMap<String, McpAuthStatus>,
  },

  /// MCP server startup progress update
  McpStartupUpdate {
    server: String,
    status: McpStartupStatus,
  },

  /// MCP server startup complete
  McpStartupComplete {
    ready: Vec<String>,
    failed: Vec<McpStartupFailure>,
    cancelled: Vec<String>,
  },

  /// Claude session initialized — carries capabilities from the init system message
  ClaudeInitialized {
    slash_commands: Vec<String>,
    skills: Vec<String>,
    tools: Vec<String>,
    models: Vec<ClaudeModelOption>,
  },

  /// Model name updated (e.g. from Claude init event)
  ModelUpdated(String),

  /// Context was compacted (summarized)
  ContextCompacted,

  /// Undo operation started
  UndoStarted { message: Option<String> },

  /// Undo operation completed
  UndoCompleted {
    success: bool,
    message: Option<String>,
  },

  /// Thread context was rolled back by N turns
  ThreadRolledBack { num_turns: u32 },

  /// Environment changed (cwd, git branch, git sha)
  EnvironmentChanged {
    cwd: Option<String>,
    git_branch: Option<String>,
    git_sha: Option<String>,
  },

  /// Rate limit event from the Claude SDK
  RateLimitEvent {
    info: orbitdock_protocol::RateLimitInfo,
  },

  /// Prompt suggestion from the Claude SDK
  PromptSuggestion { suggestion: String },

  /// Files were persisted (checkpoint saved)
  FilesPersisted { files: Vec<String> },

  /// Provider-reported worker/subagent updates that should be handled by the
  /// session loop before generic state-machine transitions.
  SubagentsUpdated { subagents: Vec<SubagentInfo> },

  /// Error occurred
  Error(String),
}

/// Runtime directives that must be consumed by the session loop, not the reducer.
#[derive(Debug, Clone)]
pub enum ConnectorRuntimeDirective {
  /// Hook started with a (possibly new) session ID — used to register managed threads
  HookSessionId(String),

  /// Provider-reported dynamic tool request that must be executed by the
  /// session loop before generic state-machine transitions.
  DynamicToolCallRequested {
    call_id: String,
    tool_name: String,
    arguments: serde_json::Value,
  },
}

/// Transport-only side effects that must never reach the reducer.
#[derive(Debug, Clone)]
pub enum ConnectorTransportEffect {
  /// Tool PTY session created (command started).
  ToolPtyCreated { tool_id: String },

  /// Raw bytes from a running tool's output (for live PTY streaming).
  /// These should be fed to the ToolPtyService for broadcast to clients.
  ToolPtyOutput { tool_id: String, bytes: Vec<u8> },

  /// Tool PTY session exited (command finished).
  ToolPtyExited {
    tool_id: String,
    exit_code: Option<i32>,
  },
}

/// Strongly typed connector output lanes.
#[derive(Debug, Clone)]
pub enum ConnectorOutput {
  State(ConnectorStateEvent),
  Runtime(ConnectorRuntimeDirective),
  Transport(ConnectorTransportEffect),
}

/// Legacy mixed connector events emitted by connectors.
///
/// Prefer the typed `ConnectorOutput` lanes for new code.
#[deprecated(note = "Use ConnectorOutput with typed lanes instead")]
#[derive(Debug, Clone)]
pub enum ConnectorEvent {
  /// Turn started
  TurnStarted,

  /// Turn completed
  TurnCompleted,

  /// Turn aborted
  TurnAborted { reason: String },

  /// New conversation row created
  ConversationRowCreated(orbitdock_protocol::conversation_contracts::ConversationRowEntry),

  /// Conversation row updated
  ConversationRowUpdated {
    row_id: String,
    entry: orbitdock_protocol::conversation_contracts::ConversationRowEntry,
  },

  /// Approval requested
  ApprovalRequested {
    request_id: String,
    approval_type: ApprovalType,
    tool_name: Option<String>,
    tool_input: Option<String>,
    command: Option<String>,
    file_path: Option<String>,
    diff: Option<String>,
    question: Option<String>,
    permission_reason: Option<String>,
    requested_permissions: Option<serde_json::Value>,
    proposed_amendment: Option<Vec<String>>,
    /// Raw permission suggestions from Claude SDK (PermissionUpdate[])
    permission_suggestions: Option<serde_json::Value>,
    /// MCP elicitation mode: "form" or "url"
    elicitation_mode: Option<String>,
    /// JSON Schema for form-mode elicitation
    elicitation_schema: Option<serde_json::Value>,
    /// URL for browser-auth-mode elicitation
    elicitation_url: Option<String>,
    /// Human-readable message from the MCP server
    elicitation_message: Option<String>,
    /// Which MCP server initiated the elicitation
    mcp_server_name: Option<String>,
    /// Network approval context: target host
    network_host: Option<String>,
    /// Network approval context: protocol (e.g. "https")
    network_protocol: Option<String>,
  },

  /// Approval cancelled by the CLI (e.g. user interrupted, agent moved on)
  ApprovalCancelled { request_id: String },

  /// Permission mode changed (e.g. plan mode entered/exited)
  PermissionModeChanged { mode: String },

  /// Token usage updated
  TokensUpdated {
    usage: TokenUsage,
    snapshot_kind: TokenUsageSnapshotKind,
  },

  /// Aggregated diff updated
  DiffUpdated(String),

  /// Plan updated
  PlanUpdated(String),

  /// Thread name updated (auto-generated by codex-core or manually set)
  ThreadNameUpdated(String),

  /// Session ended
  SessionEnded { reason: String },

  /// Skills list response
  SkillsList {
    skills: Vec<SkillsListEntry>,
    errors: Vec<SkillErrorInfo>,
  },

  /// Skills update available notification
  SkillsUpdateAvailable,

  /// MCP tools list response
  McpToolsList {
    tools: HashMap<String, McpTool>,
    resources: HashMap<String, Vec<McpResource>>,
    resource_templates: HashMap<String, Vec<McpResourceTemplate>>,
    auth_statuses: HashMap<String, McpAuthStatus>,
  },

  /// MCP server startup progress update
  McpStartupUpdate {
    server: String,
    status: McpStartupStatus,
  },

  /// MCP server startup complete
  McpStartupComplete {
    ready: Vec<String>,
    failed: Vec<McpStartupFailure>,
    cancelled: Vec<String>,
  },

  /// Claude session initialized — carries capabilities from the init system message
  ClaudeInitialized {
    slash_commands: Vec<String>,
    skills: Vec<String>,
    tools: Vec<String>,
    models: Vec<ClaudeModelOption>,
  },

  /// Model name updated (e.g. from Claude init event)
  ModelUpdated(String),

  /// Context was compacted (summarized)
  ContextCompacted,

  /// Hook started with a (possibly new) session ID — used to register managed threads
  HookSessionId(String),

  /// Undo operation started
  UndoStarted { message: Option<String> },

  /// Undo operation completed
  UndoCompleted {
    success: bool,
    message: Option<String>,
  },

  /// Thread context was rolled back by N turns
  ThreadRolledBack { num_turns: u32 },

  /// Environment changed (cwd, git branch, git sha)
  EnvironmentChanged {
    cwd: Option<String>,
    git_branch: Option<String>,
    git_sha: Option<String>,
  },

  /// Rate limit event from the Claude SDK
  RateLimitEvent {
    info: orbitdock_protocol::RateLimitInfo,
  },

  /// Prompt suggestion from the Claude SDK
  PromptSuggestion { suggestion: String },

  /// Files were persisted (checkpoint saved)
  FilesPersisted { files: Vec<String> },

  /// Provider-reported worker/subagent updates that should be handled by the
  /// session loop before generic state-machine transitions.
  SubagentsUpdated { subagents: Vec<SubagentInfo> },

  /// Provider-reported dynamic tool request that must be executed by the
  /// session loop before generic state-machine transitions.
  DynamicToolCallRequested {
    call_id: String,
    tool_name: String,
    arguments: serde_json::Value,
  },

  /// Raw bytes from a running tool's output (for live PTY streaming).
  /// These should be fed to the ToolPtyService for broadcast to clients.
  ToolPtyOutput { tool_id: String, bytes: Vec<u8> },

  /// Tool PTY session created (command started).
  ToolPtyCreated { tool_id: String },

  /// Tool PTY session exited (command finished).
  ToolPtyExited {
    tool_id: String,
    exit_code: Option<i32>,
  },

  /// Error occurred
  Error(String),
}

impl ConnectorStateEvent {
  /// Whether this event should trigger a dashboard refresh for the session.
  pub fn requires_dashboard_refresh(&self) -> bool {
    matches!(
      self,
      ConnectorStateEvent::TurnStarted
        | ConnectorStateEvent::TurnCompleted
        | ConnectorStateEvent::TurnAborted { .. }
        | ConnectorStateEvent::ApprovalRequested { .. }
        | ConnectorStateEvent::ApprovalCancelled { .. }
        | ConnectorStateEvent::SessionEnded { .. }
    )
  }
}

impl ConnectorOutput {
  /// Whether this output lane is reducer-safe.
  pub fn is_state_event(&self) -> bool {
    matches!(self, ConnectorOutput::State(_))
  }

  /// Return the reducer-safe event if this output is in the state lane.
  pub fn into_state_event(self) -> Result<ConnectorStateEvent, Self> {
    match self {
      ConnectorOutput::State(event) => Ok(event),
      other => Err(other),
    }
  }

  /// Whether this output should trigger a dashboard refresh.
  pub fn requires_dashboard_refresh(&self) -> bool {
    matches!(self, ConnectorOutput::State(event) if event.requires_dashboard_refresh())
  }
}

impl From<ConnectorStateEvent> for ConnectorOutput {
  fn from(event: ConnectorStateEvent) -> Self {
    ConnectorOutput::State(event)
  }
}

impl From<ConnectorRuntimeDirective> for ConnectorOutput {
  fn from(event: ConnectorRuntimeDirective) -> Self {
    ConnectorOutput::Runtime(event)
  }
}

impl From<ConnectorTransportEffect> for ConnectorOutput {
  fn from(event: ConnectorTransportEffect) -> Self {
    ConnectorOutput::Transport(event)
  }
}

#[allow(deprecated)]
impl ConnectorEvent {
  /// Convert a legacy mixed event into the new typed output boundary.
  pub fn into_output(self) -> ConnectorOutput {
    self.into()
  }

  /// Whether this legacy event is reducer-safe.
  pub fn is_reducer_safe(&self) -> bool {
    matches!(
      self,
      ConnectorEvent::TurnStarted
        | ConnectorEvent::TurnCompleted
        | ConnectorEvent::TurnAborted { .. }
        | ConnectorEvent::ConversationRowCreated(_)
        | ConnectorEvent::ConversationRowUpdated { .. }
        | ConnectorEvent::ApprovalRequested { .. }
        | ConnectorEvent::ApprovalCancelled { .. }
        | ConnectorEvent::PermissionModeChanged { .. }
        | ConnectorEvent::TokensUpdated { .. }
        | ConnectorEvent::DiffUpdated(_)
        | ConnectorEvent::PlanUpdated(_)
        | ConnectorEvent::ThreadNameUpdated(_)
        | ConnectorEvent::SessionEnded { .. }
        | ConnectorEvent::SkillsList { .. }
        | ConnectorEvent::SkillsUpdateAvailable
        | ConnectorEvent::McpToolsList { .. }
        | ConnectorEvent::McpStartupUpdate { .. }
        | ConnectorEvent::McpStartupComplete { .. }
        | ConnectorEvent::ClaudeInitialized { .. }
        | ConnectorEvent::ModelUpdated(_)
        | ConnectorEvent::ContextCompacted
        | ConnectorEvent::UndoStarted { .. }
        | ConnectorEvent::UndoCompleted { .. }
        | ConnectorEvent::ThreadRolledBack { .. }
        | ConnectorEvent::EnvironmentChanged { .. }
        | ConnectorEvent::RateLimitEvent { .. }
        | ConnectorEvent::PromptSuggestion { .. }
        | ConnectorEvent::FilesPersisted { .. }
        | ConnectorEvent::SubagentsUpdated { .. }
        | ConnectorEvent::Error(_)
    )
  }

  /// Whether this event should trigger a dashboard refresh for the session.
  pub fn requires_dashboard_refresh(&self) -> bool {
    matches!(
      self,
      ConnectorEvent::TurnStarted
        | ConnectorEvent::TurnCompleted
        | ConnectorEvent::TurnAborted { .. }
        | ConnectorEvent::ApprovalRequested { .. }
        | ConnectorEvent::ApprovalCancelled { .. }
        | ConnectorEvent::SessionEnded { .. }
    )
  }
}

#[allow(deprecated)]
impl From<ConnectorEvent> for ConnectorOutput {
  fn from(event: ConnectorEvent) -> Self {
    match event {
      ConnectorEvent::TurnStarted => ConnectorOutput::State(ConnectorStateEvent::TurnStarted),
      ConnectorEvent::TurnCompleted => ConnectorOutput::State(ConnectorStateEvent::TurnCompleted),
      ConnectorEvent::TurnAborted { reason } => {
        ConnectorOutput::State(ConnectorStateEvent::TurnAborted { reason })
      }
      ConnectorEvent::ConversationRowCreated(entry) => {
        ConnectorOutput::State(ConnectorStateEvent::ConversationRowCreated(entry))
      }
      ConnectorEvent::ConversationRowUpdated { row_id, entry } => {
        ConnectorOutput::State(ConnectorStateEvent::ConversationRowUpdated { row_id, entry })
      }
      ConnectorEvent::ApprovalRequested {
        request_id,
        approval_type,
        tool_name,
        tool_input,
        command,
        file_path,
        diff,
        question,
        permission_reason,
        requested_permissions,
        proposed_amendment,
        permission_suggestions,
        elicitation_mode,
        elicitation_schema,
        elicitation_url,
        elicitation_message,
        mcp_server_name,
        network_host,
        network_protocol,
      } => ConnectorOutput::State(ConnectorStateEvent::ApprovalRequested {
        request_id,
        approval_type,
        tool_name,
        tool_input,
        command,
        file_path,
        diff,
        question,
        permission_reason,
        requested_permissions,
        proposed_amendment,
        permission_suggestions,
        elicitation_mode,
        elicitation_schema,
        elicitation_url,
        elicitation_message,
        mcp_server_name,
        network_host,
        network_protocol,
      }),
      ConnectorEvent::ApprovalCancelled { request_id } => {
        ConnectorOutput::State(ConnectorStateEvent::ApprovalCancelled { request_id })
      }
      ConnectorEvent::PermissionModeChanged { mode } => {
        ConnectorOutput::State(ConnectorStateEvent::PermissionModeChanged { mode })
      }
      ConnectorEvent::TokensUpdated {
        usage,
        snapshot_kind,
      } => ConnectorOutput::State(ConnectorStateEvent::TokensUpdated {
        usage,
        snapshot_kind,
      }),
      ConnectorEvent::DiffUpdated(diff) => {
        ConnectorOutput::State(ConnectorStateEvent::DiffUpdated(diff))
      }
      ConnectorEvent::PlanUpdated(plan) => {
        ConnectorOutput::State(ConnectorStateEvent::PlanUpdated(plan))
      }
      ConnectorEvent::ThreadNameUpdated(name) => {
        ConnectorOutput::State(ConnectorStateEvent::ThreadNameUpdated(name))
      }
      ConnectorEvent::SessionEnded { reason } => {
        ConnectorOutput::State(ConnectorStateEvent::SessionEnded { reason })
      }
      ConnectorEvent::SkillsList { skills, errors } => {
        ConnectorOutput::State(ConnectorStateEvent::SkillsList { skills, errors })
      }
      ConnectorEvent::SkillsUpdateAvailable => {
        ConnectorOutput::State(ConnectorStateEvent::SkillsUpdateAvailable)
      }
      ConnectorEvent::McpToolsList {
        tools,
        resources,
        resource_templates,
        auth_statuses,
      } => ConnectorOutput::State(ConnectorStateEvent::McpToolsList {
        tools,
        resources,
        resource_templates,
        auth_statuses,
      }),
      ConnectorEvent::McpStartupUpdate { server, status } => {
        ConnectorOutput::State(ConnectorStateEvent::McpStartupUpdate { server, status })
      }
      ConnectorEvent::McpStartupComplete {
        ready,
        failed,
        cancelled,
      } => ConnectorOutput::State(ConnectorStateEvent::McpStartupComplete {
        ready,
        failed,
        cancelled,
      }),
      ConnectorEvent::ClaudeInitialized {
        slash_commands,
        skills,
        tools,
        models,
      } => ConnectorOutput::State(ConnectorStateEvent::ClaudeInitialized {
        slash_commands,
        skills,
        tools,
        models,
      }),
      ConnectorEvent::ModelUpdated(model) => {
        ConnectorOutput::State(ConnectorStateEvent::ModelUpdated(model))
      }
      ConnectorEvent::ContextCompacted => {
        ConnectorOutput::State(ConnectorStateEvent::ContextCompacted)
      }
      ConnectorEvent::UndoStarted { message } => {
        ConnectorOutput::State(ConnectorStateEvent::UndoStarted { message })
      }
      ConnectorEvent::UndoCompleted { success, message } => {
        ConnectorOutput::State(ConnectorStateEvent::UndoCompleted { success, message })
      }
      ConnectorEvent::ThreadRolledBack { num_turns } => {
        ConnectorOutput::State(ConnectorStateEvent::ThreadRolledBack { num_turns })
      }
      ConnectorEvent::EnvironmentChanged {
        cwd,
        git_branch,
        git_sha,
      } => ConnectorOutput::State(ConnectorStateEvent::EnvironmentChanged {
        cwd,
        git_branch,
        git_sha,
      }),
      ConnectorEvent::RateLimitEvent { info } => {
        ConnectorOutput::State(ConnectorStateEvent::RateLimitEvent { info })
      }
      ConnectorEvent::PromptSuggestion { suggestion } => {
        ConnectorOutput::State(ConnectorStateEvent::PromptSuggestion { suggestion })
      }
      ConnectorEvent::FilesPersisted { files } => {
        ConnectorOutput::State(ConnectorStateEvent::FilesPersisted { files })
      }
      ConnectorEvent::SubagentsUpdated { subagents } => {
        ConnectorOutput::State(ConnectorStateEvent::SubagentsUpdated { subagents })
      }
      ConnectorEvent::HookSessionId(session_id) => {
        ConnectorOutput::Runtime(ConnectorRuntimeDirective::HookSessionId(session_id))
      }
      ConnectorEvent::DynamicToolCallRequested {
        call_id,
        tool_name,
        arguments,
      } => ConnectorOutput::Runtime(ConnectorRuntimeDirective::DynamicToolCallRequested {
        call_id,
        tool_name,
        arguments,
      }),
      ConnectorEvent::ToolPtyCreated { tool_id } => {
        ConnectorOutput::Transport(ConnectorTransportEffect::ToolPtyCreated { tool_id })
      }
      ConnectorEvent::ToolPtyOutput { tool_id, bytes } => {
        ConnectorOutput::Transport(ConnectorTransportEffect::ToolPtyOutput { tool_id, bytes })
      }
      ConnectorEvent::ToolPtyExited { tool_id, exit_code } => {
        ConnectorOutput::Transport(ConnectorTransportEffect::ToolPtyExited { tool_id, exit_code })
      }
      ConnectorEvent::Error(msg) => ConnectorOutput::State(ConnectorStateEvent::Error(msg)),
    }
  }
}
