use orbitdock_protocol::conversation_contracts::ConversationRowEntry;
use orbitdock_protocol::{
  CodexConfigMode, CodexConfigSource, CodexSessionOverrides, SessionLifecycleState, SessionStatus,
  TokenUsageSnapshotKind,
};
use rusqlite::Row;

#[derive(Debug, Clone)]
pub(crate) struct StoredCodexConfigRow {
  pub codex_config_mode_raw: Option<String>,
  pub codex_config_profile: Option<String>,
  pub codex_model_provider: Option<String>,
  pub collaboration_mode: Option<String>,
  pub multi_agent: Option<bool>,
  pub personality: Option<String>,
  pub service_tier: Option<String>,
  pub developer_instructions: Option<String>,
  pub codex_config_source_raw: Option<String>,
  pub codex_config_overrides_raw: Option<String>,
}

impl StoredCodexConfigRow {
  pub(crate) fn from_row(row: &Row<'_>) -> Result<Self, rusqlite::Error> {
    Ok(Self {
      codex_config_mode_raw: row.get(0)?,
      codex_config_profile: row.get(1)?,
      codex_model_provider: row.get(2)?,
      collaboration_mode: row.get(3)?,
      multi_agent: row.get(4)?,
      personality: row.get(5)?,
      service_tier: row.get(6)?,
      developer_instructions: row.get(7)?,
      codex_config_source_raw: row.get(8)?,
      codex_config_overrides_raw: row.get(9)?,
    })
  }
}

#[derive(Debug, Clone)]
pub(crate) struct RestoredSessionRow {
  pub id: String,
  pub project_path: String,
  pub transcript_path: Option<String>,
  pub project_name: Option<String>,
  pub model: Option<String>,
  pub custom_name: Option<String>,
  pub first_prompt: Option<String>,
  pub summary: Option<String>,
  pub status: String,
  pub work_status: String,
  pub started_at: Option<String>,
  pub last_activity_at: Option<String>,
  pub last_progress_at: Option<String>,
  pub approval_policy: Option<String>,
  pub sandbox_mode: Option<String>,
  pub permission_mode: Option<String>,
  pub pending_tool_name: Option<String>,
  pub pending_tool_input: Option<String>,
  pub pending_question: Option<String>,
  pub input_tokens: i64,
  pub output_tokens: i64,
  pub cached_tokens: i64,
  pub context_window: i64,
  pub provider: String,
  pub control_mode: Option<String>,
  pub claude_sdk_session_id: Option<String>,
  pub codex_thread_id: Option<String>,
  pub end_reason: Option<String>,
  pub lifecycle_state: String,
  pub terminal_session_id: Option<String>,
  pub terminal_app: Option<String>,
  pub token_usage_snapshot_kind_str: String,
}

impl RestoredSessionRow {
  pub(crate) fn from_row(row: &Row<'_>) -> Result<Self, rusqlite::Error> {
    Ok(Self {
      id: row.get(0)?,
      project_path: row.get(1)?,
      transcript_path: row.get(2)?,
      project_name: row.get(3)?,
      model: row.get(4)?,
      custom_name: row.get(5)?,
      first_prompt: row.get(6)?,
      summary: row.get(7)?,
      status: row.get(8)?,
      work_status: row.get(9)?,
      started_at: row.get(10)?,
      last_activity_at: row.get(11)?,
      last_progress_at: row.get(12)?,
      approval_policy: row.get(13)?,
      sandbox_mode: row.get(14)?,
      permission_mode: row.get(15)?,
      pending_tool_name: row.get(16)?,
      pending_tool_input: row.get(17)?,
      pending_question: row.get(18)?,
      input_tokens: row.get(19)?,
      output_tokens: row.get(20)?,
      cached_tokens: row.get(21)?,
      context_window: row.get(22)?,
      provider: row.get(23)?,
      control_mode: row.get(24)?,
      claude_sdk_session_id: row.get(25)?,
      codex_thread_id: row.get(26)?,
      end_reason: row.get(27)?,
      lifecycle_state: row.get(28)?,
      terminal_session_id: row.get(29)?,
      terminal_app: row.get(30)?,
      token_usage_snapshot_kind_str: row.get(31)?,
    })
  }
}

#[derive(Debug, Clone)]
pub(crate) struct ActiveSessionRow {
  pub id: String,
  pub provider: String,
  pub status: String,
  pub work_status: String,
  pub control_mode: Option<String>,
  pub lifecycle_state: String,
  pub project_path: String,
  pub transcript_path: Option<String>,
  pub project_name: Option<String>,
  pub model: Option<String>,
  pub custom_name: Option<String>,
  pub first_prompt: Option<String>,
  pub codex_thread_id: Option<String>,
  pub started_at: Option<String>,
  pub last_activity_at: Option<String>,
  pub last_progress_at: Option<String>,
  pub approval_policy: Option<String>,
  pub sandbox_mode: Option<String>,
  pub permission_mode: Option<String>,
  pub pending_tool_name: Option<String>,
  pub pending_tool_input: Option<String>,
  pub pending_question: Option<String>,
  pub input_tokens: i64,
  pub output_tokens: i64,
  pub cached_tokens: i64,
  pub context_window: i64,
  pub token_usage_snapshot_kind_str: String,
}

impl ActiveSessionRow {
  pub(crate) fn from_row(row: &Row<'_>) -> Result<Self, rusqlite::Error> {
    Ok(Self {
      id: row.get(0)?,
      provider: row.get(1)?,
      status: row.get(2)?,
      work_status: row.get(3)?,
      control_mode: row.get(4)?,
      lifecycle_state: row.get(5)?,
      project_path: row.get(6)?,
      transcript_path: row.get(7)?,
      project_name: row.get(8)?,
      model: row.get(9)?,
      custom_name: row.get(10)?,
      first_prompt: row.get(11)?,
      codex_thread_id: row.get(12)?,
      started_at: row.get(13)?,
      last_activity_at: row.get(14)?,
      last_progress_at: row.get(15)?,
      approval_policy: row.get(16)?,
      sandbox_mode: row.get(17)?,
      permission_mode: row.get(18)?,
      pending_tool_name: row.get(19)?,
      pending_tool_input: row.get(20)?,
      pending_question: row.get(21)?,
      input_tokens: row.get(22)?,
      output_tokens: row.get(23)?,
      cached_tokens: row.get(24)?,
      context_window: row.get(25)?,
      token_usage_snapshot_kind_str: row.get(26)?,
    })
  }
}

#[derive(Debug)]
pub(crate) struct RestoredSession {
  pub id: String,
  pub provider: String,
  pub status: String,
  pub work_status: String,
  pub control_mode: orbitdock_protocol::SessionControlMode,
  pub lifecycle_state: SessionLifecycleState,
  pub project_path: String,
  pub transcript_path: Option<String>,
  pub project_name: Option<String>,
  pub model: Option<String>,
  pub custom_name: Option<String>,
  pub summary: Option<String>,
  pub codex_thread_id: Option<String>,
  pub claude_sdk_session_id: Option<String>,
  pub started_at: Option<String>,
  pub last_activity_at: Option<String>,
  pub last_progress_at: Option<String>,
  pub approval_policy: Option<String>,
  pub sandbox_mode: Option<String>,
  pub permission_mode: Option<String>,
  pub collaboration_mode: Option<String>,
  pub multi_agent: Option<bool>,
  pub personality: Option<String>,
  pub service_tier: Option<String>,
  pub developer_instructions: Option<String>,
  pub codex_config_mode: Option<CodexConfigMode>,
  pub codex_config_profile: Option<String>,
  pub codex_model_provider: Option<String>,
  pub codex_config_source: Option<CodexConfigSource>,
  pub codex_config_overrides: Option<CodexSessionOverrides>,
  pub input_tokens: i64,
  pub output_tokens: i64,
  pub cached_tokens: i64,
  pub context_window: i64,
  pub token_usage_snapshot_kind: TokenUsageSnapshotKind,
  pub pending_tool_name: Option<String>,
  pub pending_tool_input: Option<String>,
  pub pending_question: Option<String>,
  pub pending_approval_id: Option<String>,
  pub rows: Vec<ConversationRowEntry>,
  pub forked_from_session_id: Option<String>,
  pub current_diff: Option<String>,
  pub current_plan: Option<String>,
  pub turn_count: u64,
  pub turn_diffs: Vec<(String, String, i64, i64, i64, i64, TokenUsageSnapshotKind)>,
  pub git_branch: Option<String>,
  pub git_sha: Option<String>,
  pub current_cwd: Option<String>,
  pub first_prompt: Option<String>,
  pub last_message: Option<String>,
  pub end_reason: Option<String>,
  pub effort: Option<String>,
  pub terminal_session_id: Option<String>,
  pub terminal_app: Option<String>,
  pub approval_version: u64,
  pub unread_count: u64,
  pub mission_id: Option<String>,
  pub issue_identifier: Option<String>,
  pub allow_bypass_permissions: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DirectClaudeOwner {
  pub session_id: String,
  pub status: SessionStatus,
  pub lifecycle_state: SessionLifecycleState,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DirectCodexOwner {
  pub session_id: String,
  pub status: SessionStatus,
  pub lifecycle_state: SessionLifecycleState,
}

#[derive(Debug)]
pub(crate) struct RestoredSessionParts {
  pub id: String,
  pub provider: String,
  pub status: String,
  pub work_status: String,
  pub control_mode: orbitdock_protocol::SessionControlMode,
  pub lifecycle_state: SessionLifecycleState,
  pub project_path: String,
  pub transcript_path: Option<String>,
  pub project_name: Option<String>,
  pub model: Option<String>,
  pub custom_name: Option<String>,
  pub summary: Option<String>,
  pub codex_thread_id: Option<String>,
  pub claude_sdk_session_id: Option<String>,
  pub started_at: Option<String>,
  pub last_activity_at: Option<String>,
  pub last_progress_at: Option<String>,
  pub approval_policy: Option<String>,
  pub sandbox_mode: Option<String>,
  pub permission_mode: Option<String>,
  pub collaboration_mode: Option<String>,
  pub multi_agent: Option<bool>,
  pub personality: Option<String>,
  pub service_tier: Option<String>,
  pub developer_instructions: Option<String>,
  pub codex_config_mode: Option<CodexConfigMode>,
  pub codex_config_profile: Option<String>,
  pub codex_model_provider: Option<String>,
  pub codex_config_source: Option<CodexConfigSource>,
  pub codex_config_overrides: Option<CodexSessionOverrides>,
  pub input_tokens: i64,
  pub output_tokens: i64,
  pub cached_tokens: i64,
  pub context_window: i64,
  pub token_usage_snapshot_kind: TokenUsageSnapshotKind,
  pub pending_tool_name: Option<String>,
  pub pending_tool_input: Option<String>,
  pub pending_question: Option<String>,
  pub pending_approval_id: Option<String>,
  pub rows: Vec<ConversationRowEntry>,
  pub forked_from_session_id: Option<String>,
  pub current_diff: Option<String>,
  pub current_plan: Option<String>,
  pub turn_count: u64,
  pub turn_diffs: Vec<(String, String, i64, i64, i64, i64, TokenUsageSnapshotKind)>,
  pub git_branch: Option<String>,
  pub git_sha: Option<String>,
  pub current_cwd: Option<String>,
  pub first_prompt: Option<String>,
  pub last_message: Option<String>,
  pub end_reason: Option<String>,
  pub effort: Option<String>,
  pub terminal_session_id: Option<String>,
  pub terminal_app: Option<String>,
  pub approval_version: u64,
  pub unread_count: u64,
  pub mission_id: Option<String>,
  pub issue_identifier: Option<String>,
  pub allow_bypass_permissions: bool,
}
